<a href="https://colab.research.google.com/github/turuuschs/Sict-NLP/blob/master/Course_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Бичвэр ангилал

## Шаардлагатай сангууд

In [0]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import re

## Дата

In [21]:
data = pd.read_csv("mongolian_news.csv",encoding='UTF-8')
data = data[['CATEGORY','TITLE']]
data.CATEGORY.unique()
data.groupby('CATEGORY').describe()

TITLE  ...     
                                 count  ... freq
CATEGORY                                ...     
 2. Нийгмийн тэнцвэрт байдал      1  ...    1
Дэлхий                            4952  ...    5
Нийгэм                            8184  ...   58
Спорт                             4946  ...   10
Улс төр                          11436  ...   21
Шар мэдээ                         3867  ...    5
Эдийн засаг                       8986  ...   20
Энтертайнмент                     8248  ...    6

[8 rows x 4 columns]

## Мэдээний ангилалуудаа тоон утгаар кодлов

In [22]:
data['NUM_CATEGORY']= data.CATEGORY.map({
    'Дэлхий': 0,
    'Нийгэм': 1,
    'Спорт': 2,
    'Улс төр': 3,
    'Шар мэдээ': 4,
    'Эдийн засаг': 5,
    'Энтертайнмент': 6,
})
data.head()

CATEGORY                                              TITLE  NUM_CATEGORY
0  Улс төр  УИХ-ын Төсвийн байнгын хорооны хуралдаанаар өн...           3.0
1  Улс төр  Төрийн аудитын хуулийн шинэчилсэн найруулгын т...           3.0
2  Улс төр  Улсын Их Хурлын гишүүн Л.Энх-Амгалан нарын 7 г...           3.0
3  Улс төр  анхны хэлэлцүүлгийг хийв.  Төслийн талаар гишү...           3.0
4  Улс төр  Аудитын байгууллагын өнөөгийн хүчин чадал, нөө...           3.0

In [0]:
data = data[data['TITLE'].notnull()]
data = data[data['NUM_CATEGORY'].notnull()]

## Сургалт, тестийн дата харьцаа 80/20

In [0]:
x_train, x_test, y_train, y_test = train_test_split(data.TITLE, data.NUM_CATEGORY, test_size = 0.2, random_state=0)

## Bigram модел ашиглан Bag of Word вектор үүсгэв 

In [0]:
vect = CountVectorizer(ngram_range=(2,2))
X_train = vect.fit_transform(x_train)
xTrain = np.array(X_train)
X_test = vect.transform(x_test)

## Сургалт ба тест

In [0]:
mnb = MultinomialNB(alpha=0.2)
mnb.fit(X_train,y_train)
result = mnb.predict(X_test)

## Моделийн үр дүн

In [27]:
print (accuracy_score(result,y_test))
print (confusion_matrix(y_test, result))

0.7113789016199131
[[ 694   78   11   41   38   48   47]
 [  91 1118    5  195   33  109   72]
 [  36   40  753   36   32   19   64]
 [  37  143    6 1829   26  167   63]
 [ 114   63   45  150  241   33  167]
 [  54  107    9  202   32 1332   73]
 [  84   71   35   84  104   58 1235]]


# Тест
## Текст олборлосон сайтаас өөр сайтаас мэдээ тестлэж үзэв.

In [0]:
def predict_news(news):
    test = vect.transform(news)
    pred = mnb.predict(test)
    if pred == 0:
      return 'Дэлхий'
    if pred == 1:
      return 'Нийгэм'
    if pred == 2:
      return 'Спорт'
    if pred == 3:
      return 'Улс төр'
    if pred == 4:
      return 'Шар мэдээ'
    if pred == 5:
      return 'Эдийн засаг'
    if pred == 6:
      return 'Энтертайнмент'

In [29]:
x = ["НҮБ-ын харьяа Дэлхийн Хүнсний Хөтөлбөрийн гүйцэтгэх захирал Дэвид Бисли коронавирусийн цар тахлын улмаас дэлхий даяар 130 сая хүн өлсгөлөнд нэрвэгдэх төлөвтэй байгааг Мягмар гарагт мэдэгджээ."]
r = predict_news(x)
print (r)

Дэлхий


In [30]:
x = ["Лозанн-2020 Залуучуудын өвлийн Олимпийн наадмын, Монголын баг тамирчид өрсөлдөж буй Гүйлтийн цанын 2 дахь уралдаан өчигдөр /01.19/ боллоо."]
r = predict_news(x)
print (r)

Спорт


In [31]:
x = ["Монгол Улсын засаг захиргаа, нутаг дэвсгэрийн нэгж, түүний удирдлагын тухай хуулийн шинэчилсэн найруулгын төслийг УИХ-д өргөн барьсан талаараа УИХ-ын гишүүн Д.Тогтохсүрэн мэдээлэл хийлээ."]
r = predict_news(x)
print (r)

Улс төр
